[theme]
primaryColor = "#150169"         # Azul Colmédicos
backgroundColor = "#EFF2F7"      # Fondo claro
secondaryBackgroundColor = "#D6DBE9"  # Panel lateral
textColor = "#262730"            # Texto
font = "sans serif"              # Fuente (puede ser: sans serif, serif, monospace)
